### ISSUE TITLE
question - which mac are you using?

### ISSUE THREAD

**Issue by Dexdev08** [ctmakro/tensorflow_custom_python_wheel_build#5]
Hi - wanted to check which mac are you using?  I have an old macbook air, circa 2013 (with mavericks... considering upgrading to sierra...)

also, a bit of a noob - how would i know if avx and avx2 and the other compiler options are available on my machine?

**Comment by ctmakro** [comment]
@Dexdev08 
MBP2015 Retina. Google the name of your CPU and find out the instruction set it supports.
